package dev.sleepy.app.patches

import dev.sleepy.app.model.BlocklistGate
import dev.sleepy.app.model.BlocklistRule
import dev.sleepy.app.model.BlocklistRuleKind
import dev.sleepy.app.model.PatchItem

/**
 * The network blocklist as data: every pattern the generated interceptor scans for, and what
 * blocking it prevents.
 *
 * These were private lists inside [DiscordBlocklistPatch], which was enough while the whole table
 * was compiled into every build. Per-item selection needs addressable entries, with a description
 * to show, an identity to key a saved selection on, and enough structure to compile a subset, so
 * the lists live here and the generator reads them.
 *
 * Transcribed from `quirky-noether/discord/patches/blocklist.py`, which is the source of every
 * following description; the entries that file lists without a per-entry note are marked as such
 * rather than having one written for them. The order is the reference's order, and the comparison
 * depends on it: the interceptor is generated by walking these lists, and its output is compared
 * line for line against the method the reference build shipped.
 *
 * Host rules are tested against every request; API rules only against URLs that contain `/api/`
 * and do not look proxied. That asymmetry is why [dev.sleepy.app.model.BlocklistCoverage] uses a
 * rule's kind to determine whether one rule makes another redundant.
 */
object DiscordBlocklistRules {

    /** Heading for the host rules in the item list. */
    private const val HOST_GROUP = "Hosts (blocked on every request)"

    /** Heading for the API path rules in the item list. */
    private const val API_GROUP = "API paths (blocked on Discord API calls only)"

    /**
     * Rules matched anywhere in the request URL, on every request.
     *
     * api.spotify.com and dealer.spotify.com are here on purpose: breaking the Spotify integration
     * (its REST API and the listen-along WebSocket) is intended, not an oversight. The desktop
     * reference notes that an audit flagged it as a feature regression and the user confirmed the
     * block is deliberate.
     */
    val HOST_RULES: List<BlocklistRule> = listOf(
        rule(BlocklistRuleKind.HOST, "api.spotify.com", "Spotify's Web API. Blocked deliberately: the desktop " +
            "reference notes an audit flagged the Spotify break as a feature regression and the user confirmed " +
            "it is intended."),
        rule(
            BlocklistRuleKind.HOST, "dealer.spotify.com",
            "Spotify's listen-along WebSocket (the dealer endpoint), " +
                "blocked as part of the same deliberate Spotify break."
        ),
        rule(
            BlocklistRuleKind.HOST, "img.litix.io",
            "The video quality-of-experience beacon (Mux/Litix) that the " +
                "media player hit while a video played."
        ),
        rule(BlocklistRuleKind.HOST, "firebaselogging", "Firebase Analytics, matched as a prefix rather than a whole " +
            "host: the SDK logs to firebaselogging-pa.googleapis.com, which the literal host name never " +
            "matched. Firebase Installations and the FCM/mtalk hosts are deliberately absent, because blocking " +
            "those breaks push notifications."),
        rule(
            BlocklistRuleKind.HOST, "app-measurement.com",
            "Firebase Analytics' measurement host."
        ),
        rule(
            BlocklistRuleKind.HOST, "google-analytics.com",
            "Google Analytics. Matching the bare domain covers the " +
                "ssl., www. and region1. subdomains that carry the traffic."
        ),
        rule(BlocklistRuleKind.HOST, "sentry.io", "Sentry, matched bare rather than as ingest.sentry.io: Sentry " +
            "moved to regional DSN hosts (o<org>.ingest.us.sentry.io, .de., .eu.) that the old pattern never " +
            "matched at all. This covers every DSN form and the documentation."),
        rule(BlocklistRuleKind.HOST, "sentry-cdn.com", "Sentry's replay bundle CDN."),
        rule(
            BlocklistRuleKind.HOST, "appsflyer.com",
            "AppsFlyer install attribution. The SDK's init is already " +
                "no-op'd; this covers its network side."
        ),
        rule(
            BlocklistRuleKind.HOST, "appsflyersdk.com",
            "AppsFlyer's SDK host, blocked with the rest of its " +
                "attribution."
        ),
        rule(
            BlocklistRuleKind.HOST, "onelink.me",
            "AppsFlyer's OneLink short domain, the links install attribution " +
                "is delivered through."
        ),
        rule(
            BlocklistRuleKind.HOST, "qualtrics.com",
            "Qualtrics, the survey platform Discord serves its " +
                "questionnaires from."
        ),
        rule(BlocklistRuleKind.HOST, "datadog.discord.tools", "Discord's Datadog APM intake."),
        rule(BlocklistRuleKind.HOST, "b.stats.paypal.com", "PayPal's conversion-tracking beacon."),
        rule(
            BlocklistRuleKind.HOST, "c.paypal.com",
            "The PayPal FraudNet script that the in-app checkout webview " +
                "loaded."
        ),
        rule(BlocklistRuleKind.HOST, "pagead2.googlesyndication.com", "Google Mobile Ads' attribution beacon. Only " +
            "reachable if the ads path were live (it is stubbed), but the host string is still in the DEX."),
        rule(
            BlocklistRuleKind.HOST, "api.amplitude.com",
            "Amplitude's analytics intake. The reference lists it with " +
                "the analytics hosts and gives no per-entry note."
        ),
        rule(
            BlocklistRuleKind.HOST, "api.segment.io",
            "Segment's event intake, listed with the analytics hosts."
        ),
        rule(
            BlocklistRuleKind.HOST, "client-analytics.braintreegateway.com",
            "Braintree's client analytics, listed " +
                "with the payment hosts."
        ),
        rule(
            BlocklistRuleKind.HOST, "app.adjust.com",
            "Adjust's attribution intake, listed with the ad-attribution " +
                "hosts."
        ),
    )

    /**
     * Rules matched only on Discord API URLs - those containing `/api/` and not `/external/`.
     *
     * Without that gate a rule such as `/track` also returns a 204 for a CDN attachment called
     * `track1.mp3`, which breaks it; see [GATES].
     */
    val API_RULES: List<BlocklistRule> = listOf(
        rule(
            BlocklistRuleKind.API, "/science",
            "Discord's science-event collector: every analytics event the client " +
                "queues is uploaded here, and blocking it drops the whole batch."
        ),
        rule(
            BlocklistRuleKind.API, "/track",
            "The generic tracking endpoint. The /api/ gate is what keeps this rule " +
                "off CDN files, so an attachment named track1.mp3 is unaffected."
        ),
        rule(
            BlocklistRuleKind.API, "scienc0",
            "The obfuscated spelling of the science collector some builds use. " +
                "Matched without a leading slash because it appears mid-path."
        ),
        rule(
            BlocklistRuleKind.API, "/affinit",
            "The guild-affinity endpoints: the server- and friend-interest graph " +
                "the client builds to personalize what it shows."
        ),
        rule(BlocklistRuleKind.API, "/analytics_sessions", "Session analytics reporting."),
        rule(BlocklistRuleKind.API, "/metrics", "The client metrics upload. MonitoringAgent POSTs /metrics/v2 every " +
            "two minutes, and the reference records that this one was live rather than already dead."),
        rule(
            BlocklistRuleKind.API, "/beaker",
            "The client_telemetry heartbeat, a plain HTTP POST outside the " +
                "/science queue. The reference records it as live and unblocked before this rule."
        ),
        rule(BlocklistRuleKind.API, "/content-inventory/users/@me/spotify", "Discord's own Spotify content inventory " +
            "- the one Spotify endpoint that is not on a Spotify host and so is not caught above."),
        rule(BlocklistRuleKind.API, "/connections/spotify", "The Spotify access-token endpoint on discord.com. " +
            "Without this credential the client cannot use the Spotify Web API even if it can reach it."),
        rule(
            BlocklistRuleKind.API, "/users/@me/activities/statistics",
            "The activity-statistics upload."
        ),
        rule(BlocklistRuleKind.API, "/users/@me/survey", "The app-rating survey endpoint."),
        rule(BlocklistRuleKind.API, "/users/@me/embedded-survey", "The embedded survey endpoint."),
        rule(BlocklistRuleKind.API, "/ads/", "Ad attribution calls."),
        rule(
            BlocklistRuleKind.API, "/debug/temporal",
            "The debug endpoints the client exposes for its Temporal " +
                "workflows."
        ),
        rule(
            BlocklistRuleKind.API, "/storefront",
            "Storefront data: the shop's catalog, its products and their " +
                "prices."
        ),
        rule(
            BlocklistRuleKind.API, "/quest",
            "Quest endpoints - the tasks the client shows a user for rewards."
        ),
        rule(
            BlocklistRuleKind.API, "/quest-home",
            "The Quest Home screen's own endpoint, separate from the quest " +
                "endpoints above."
        ),
        rule(
            BlocklistRuleKind.API, "/promotion",
            "Promotions: the discounted offers the client surfaces on the " +
                "store and home screens."
        ),
        rule(BlocklistRuleKind.API, "/bogo-promotions", "Buy-one-get-one promotions."),
        rule(BlocklistRuleKind.API, "/shop", "Shop endpoints."),
        rule(BlocklistRuleKind.API, "/game-shop", "The server's game shop."),
        rule(
            BlocklistRuleKind.API, "/collectibles",
            "Collectibles - the profile decorations and shop items Discord " +
                "sells."
        ),
        rule(BlocklistRuleKind.API, "-collectibles", "The hyphenated collectibles endpoints the slash-prefixed rule " +
            "above cannot match: /users/@me/claim-premium-collectibles-product and " +
            "/users/@me/valid-collectibles-gift-recipients-batch. Found by diffing every API-shaped path in the " +
            "bundle against the rules."),
        rule(
            BlocklistRuleKind.API, "/wishlist",
            "The wishlist endpoints - the list of shop items a user saved for " +
                "later."
        ),
        rule(
            BlocklistRuleKind.API, "/virtual_currency",
            "Orbs, the virtual currency the quests pay out."
        ),
        rule(BlocklistRuleKind.API, "/perks", "Nitro perks."),
        rule(BlocklistRuleKind.API, "/reward", "Reward claims."),
        rule(BlocklistRuleKind.API, "/users/@me/billing", "The user's own billing endpoints."),
        rule(BlocklistRuleKind.API, "/billing", "Billing endpoints in general."),
        rule(BlocklistRuleKind.API, "/google-play/", "Play Store in-app purchase calls."),
        rule(BlocklistRuleKind.API, "/store/", "Store listings and price tiers."),
        rule(
            BlocklistRuleKind.API, "/entitlement",
            "Entitlements - the record of what the account owns."
        ),
        rule(BlocklistRuleKind.API, "/gift", "Gifting endpoints."),
        rule(BlocklistRuleKind.API, "/subscription", "Subscription endpoints."),
        rule(
            BlocklistRuleKind.API, "/guild-role-subscription",
            "Server subscriptions, where a server sells access " +
                "to its roles."
        ),
        rule(BlocklistRuleKind.API, "/guild_role_subscriptions", "The underscore spelling of the same " +
            "server-subscription endpoints; some call sites use it and the hyphenated rule above does not match " +
            "it."),
        rule(BlocklistRuleKind.API, "/guild_boosting", "Server boosting."),
        rule(BlocklistRuleKind.API, "/skus", "The SKU catalog - the list of what can be bought."),
        rule(BlocklistRuleKind.API, "/purchases", "Purchase records."),
        rule(BlocklistRuleKind.API, "/checkout", "Checkout."),
        rule(BlocklistRuleKind.API, "/payment", "Payment endpoints."),
        rule(
            BlocklistRuleKind.API, "/user-offer",
            "Personalized offers: the discount banners the client shows a " +
                "user it is trying to convert."
        ),
        rule(BlocklistRuleKind.API, "/referral", "Referral programs."),
        rule(BlocklistRuleKind.API, "/nitro", "Nitro."),
        rule(BlocklistRuleKind.API, "/guilds/premium", "Premium server (boost) endpoints."),
        rule(BlocklistRuleKind.API, "/boost", "Boosts."),
        rule(BlocklistRuleKind.API, "/premium", "Premium endpoints in general."),
        rule(BlocklistRuleKind.API, "/typing", "The typing indicator. With it blocked the client's own typing events " +
            "never leave the device, so nobody else sees this user typing. It does not affect the typing " +
            "indicators other people send, which arrive over the gateway connection."),
        rule(
            BlocklistRuleKind.API, "/creator-monetization",
            "The hyphenated spelling of the creator monetization " +
                "endpoints, which a plain contains of another rule does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/role-subscriptions",
            "The hyphenated spelling of the server role-subscription " +
                "endpoints, which \"/guild-role-subscription\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/virtual-currency",
            "The hyphenated spelling of the orb endpoints, which " +
                "\"/virtual_currency\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/outbound-promotions",
            "The hyphenated spelling of the outbound promotion " +
                "endpoints, which \"/promotion\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/partner-perks",
            "The hyphenated spelling of the partner perks endpoints, which " +
                "\"/perks\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/program-rewards",
            "The hyphenated spelling of the program reward endpoints, " +
                "which \"/reward\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/tenure-reward",
            "The hyphenated spelling of the tenure reward endpoint, which " +
                "\"/reward\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/claim-reward",
            "The hyphenated spelling of the claim-reward endpoint, which " +
                "\"/reward\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/store-listing",
            "The hyphenated spelling of the store-listing endpoints, which " +
                "\"/store/\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/application-storefront",
            "The hyphenated spelling of the application " +
                "storefront endpoint, which \"/storefront\" does not match."
        ),
        rule(
            BlocklistRuleKind.API, "/applied-boosts",
            "The hyphenated spelling of the applied-boosts endpoint, " +
                "which \"/boost\" does not match."
        ),
        rule(BlocklistRuleKind.API, "/powerups", "Server powerups."),
        rule(
            BlocklistRuleKind.API, "/activities/statistics",
            "The short spelling of the activity-statistics " +
                "endpoint; the /users/@me form above does not match every call site."
        ),
    )

    /**
     * Every rule, in the order the interceptor applies them.
     *
     * Host rules first, then API rules, because that is the order the reference emits them in and
     * the order the generated method is checked against.
     */
    val ALL: List<BlocklistRule> = HOST_RULES + API_RULES

    /**
     * The two prefix gates the interceptor applies before any rule.
     *
     * Neither is a rule and neither can be switched off: they are what confines the API rules to
     * the requests they were written for, and dropping one does not block less; it blocks
     * the wrong things. They are listed here as data so the UI can show them as locked rows rather
     * than leaving their behavior invisible; see each gate's [BlocklistGate.reason].
     */
    val GATES: List<BlocklistGate> = listOf(
        BlocklistGate(
            pattern = "/api/",
            label = "/api/ - API rules apply only to Discord API calls",
            description = "The test that decides whether a request is a Discord API call. The API path " +
                "rules are consulted only when the URL contains /api/, so a rule such as /shop cannot " +
                "match an ordinary content URL.",
            reason = "Required: the API path rules are bare substrings, so without this gate they would " +
                "match any URL that happens to contain one. A CDN attachment named track1.mp3 or " +
                "shop.png contains /track and /shop, and answering it with an empty 204 would break " +
                "that image."
        ),
        BlocklistGate(
            pattern = "/external/",
            label = "/external/ - proxied URLs are never treated as API calls",
            description = "The test that keeps the API path rules off Discord's media proxy URLs. A " +
                "proxied URL is not an API call, even when it contains /api/ and a blocked word.",
            reason = "Required: the media proxy embeds the origin URL after /external/<signature>/, so a " +
                "proxied image whose source path contains /api/ and a blocked word would otherwise be " +
                "answered with an empty 204 and render broken."
        )
    )

    /**
     * Every rule as a selectable item, grouped by how it is matched.
     *
     * The rule's pattern is its label and its identity: it is the whole of the rule, and it is what
     * a saved selection records. The gates are not items - they cannot be selected or deselected,
     * so they are rows without a switch rather than items that are permanently on.
     */
    fun items(setId: String): List<PatchItem> =
        HOST_RULES.map { item(it, setId, HOST_GROUP) } +
            API_RULES.map { item(it, setId, API_GROUP) }

    private fun item(rule: BlocklistRule, setId: String, group: String) = PatchItem(
        setId = setId,
        identity = rule.identity,
        label = rule.pattern,
        group = group,
        description = rule.description
    )

    private fun rule(kind: BlocklistRuleKind, pattern: String, description: String) =
        BlocklistRule(kind = kind, pattern = pattern, description = description)
}
